<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Element extends \App\Entity\Element implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Element' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Element' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Element' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Element' . "\0" . 'monstres', '' . "\0" . 'App\\Entity\\Element' . "\0" . 'attaques', '' . "\0" . 'App\\Entity\\Element' . "\0" . 'habitats'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Element' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Element' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Element' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Element' . "\0" . 'monstres', '' . "\0" . 'App\\Entity\\Element' . "\0" . 'attaques', '' . "\0" . 'App\\Entity\\Element' . "\0" . 'habitats'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Element $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\Element
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(string $image): \App\Entity\Element
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getMonstres(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMonstres', []);

        return parent::getMonstres();
    }

    /**
     * {@inheritDoc}
     */
    public function addMonstre(\App\Entity\Monstre $monstre): \App\Entity\Element
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMonstre', [$monstre]);

        return parent::addMonstre($monstre);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMonstre(\App\Entity\Monstre $monstre): \App\Entity\Element
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMonstre', [$monstre]);

        return parent::removeMonstre($monstre);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttaques(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttaques', []);

        return parent::getAttaques();
    }

    /**
     * {@inheritDoc}
     */
    public function addAttaque(\App\Entity\Attaque $attaque): \App\Entity\Element
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAttaque', [$attaque]);

        return parent::addAttaque($attaque);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAttaque(\App\Entity\Attaque $attaque): \App\Entity\Element
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAttaque', [$attaque]);

        return parent::removeAttaque($attaque);
    }

    /**
     * {@inheritDoc}
     */
    public function getHabitats(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHabitats', []);

        return parent::getHabitats();
    }

    /**
     * {@inheritDoc}
     */
    public function addHabitat(\App\Entity\Habitat $habitat): \App\Entity\Element
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addHabitat', [$habitat]);

        return parent::addHabitat($habitat);
    }

    /**
     * {@inheritDoc}
     */
    public function removeHabitat(\App\Entity\Habitat $habitat): \App\Entity\Element
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeHabitat', [$habitat]);

        return parent::removeHabitat($habitat);
    }

}
