<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGxWo5o1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGxWo5o1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGxWo5o1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGxWo5o1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGxWo5o1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GxWo5o1',
    'container.build_id' => '806d0648',
    'container.build_time' => 1555711389,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGxWo5o1');
