<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHo2Z2kx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHo2Z2kx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHo2Z2kx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHo2Z2kx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHo2Z2kx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ho2Z2kx',
    'container.build_id' => '859cd0af',
    'container.build_time' => 1556834967,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHo2Z2kx');
