<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMwYWRir\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMwYWRir/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMwYWRir.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMwYWRir\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMwYWRir\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MwYWRir',
    'container.build_id' => 'c0b7c065',
    'container.build_time' => 1556757051,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMwYWRir');
